# Generated by Django 4.2.1 on 2023-05-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_nombre', models.CharField(max_length=25)),
                ('empleado_apellido', models.CharField(max_length=50)),
                ('empleado_telefono', models.CharField(max_length=20)),
                ('empleado_fechainicio', models.DateField(db_column='empleado_fechaInicio')),
                ('empleado_fechafin', models.DateField(blank=True, db_column='empleado_fechaFin', null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modulo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo_nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('operacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('operacion_nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=50)),
                ('usuario_contrasena', models.CharField(max_length=50)),
                ('usuario_fechacreacion', models.DateTimeField(db_column='usuario_fechaCreacion')),
                ('usuario_estado', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloOperacion',
            fields=[
                ('operacion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.operacion')),
            ],
            options={
                'db_table': 'modulo_operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolModulo',
            fields=[
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.modulo')),
            ],
            options={
                'db_table': 'rol_modulo',
                'managed': False,
            },
        ),
    ]
