# Generated by Django 4.2.1 on 2023-06-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
    ]
